openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'realmeet'
servers:
  - url: 'localhost:3000'
paths:
  /rooms/{id}:
    get:
      summary: 'Return an room by ID'
      operationId: getRoom
      tags:
        - room
      parameters:
        - $ref: '#/components/parameters/apiKey'
        - name: id
          in: path
          description: ID of the room
          required: true
          schema:
            type: integer
            format: int64

      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        404:
          description: NOT FOUND

    put:
      summary: 'Update an room by ID'
      operationId: updateRoom
      tags:
        - room
      parameters:
        - $ref: '#/components/parameters/apiKey'
        - name: id
          in: path
          description: ID of the room
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoomDTO'
        required: true
      responses:
        '204':
          description: 'UPDATED SUCCESSFULLY'
        404:
          description: NOT FOUND
        422:
          $ref: '#/components/responses/UnprocessableEntity'

    delete:
      summary: 'Delete an room by ID'
      operationId: deleteRoom
      tags:
        - room
      parameters:
        - $ref: '#/components/parameters/apiKey'
        - name: id
          in: path
          description: ID of the room
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 'DELETED SUCCESSFULLY'
        404:
          description: NOT FOUND

  /rooms:
    post:
      summary: 'Create an room'
      operationId: createRoom
      tags:
        - room
      parameters:
        - $ref: '#/components/parameters/apiKey'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoomDTO'
        required: true
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDTO'
        422:
          $ref: '#/components/responses/UnprocessableEntity'

  /allocations:
    get:
      summary: 'Lists allocations'
      operationId: listAllocations
      tags:
        - allocation
      parameters:
        - $ref: '#/components/parameters/apiKey'
        - name: employeeEmail
          in: query
          description: Email of the employee
          schema:
            type: string
        - name: roomId
          in: query
          description: Id of the room
          schema:
            type: integer
            format: int64
        - name: startAt
          in: query
          description: Allocation start time
          schema:
            type: string
            format: date
        - name: endtAt
          in: query
          description: Allocation end time
          schema:
            type: string
            format: date
        - $ref: '#/components/parameters/orderBy'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/page'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AllocationDTO'

    post:
      summary: 'Create an allocation'
      operationId: createAllocation
      tags:
        - allocation
      parameters:
        - $ref: '#/components/parameters/apiKey'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAllocationDTO'
        required: true
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllocationDTO'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        404:
          description: NOT FOUND

  /allocations/{id}:
    put:
      summary: 'Update an allocation by ID'
      operationId: updateAllocation
      tags:
        - allocation
      parameters:
        - $ref: '#/components/parameters/apiKey'
        - name: id
          in: path
          description: ID of the allocation
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAllocationDTO'
        required: true
      responses:
        '204':
          description: 'UPDATED SUCCESSFULLY'
        404:
          description: NOT FOUND
        422:
          $ref: '#/components/responses/UnprocessableEntity'

    delete:
      summary: 'Delete an allocation by ID'
      operationId: deleteAllocation
      tags:
        - allocation
      parameters:
        - $ref: '#/components/parameters/apiKey'
        - name: id
          in: path
          description: ID of the allocation
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 'DELETED SUCCESSFULLY'
        404:
          description: NOT FOUND
        422:
          $ref: '#/components/responses/UnprocessableEntity'

components:
  schemas:
    UpdateRoomDTO:
      type: object
      properties:
        name:
          type: string
        seats:
          type: integer

    CreateRoomDTO:
      type: object
      allOf:
       - $ref: '#/components/schemas/UpdateRoomDTO'

    RoomDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        seats:
          type: integer

    UpdateAllocationDTO:
      type: object
      properties:
        subject:
          type: string
        startAt:
          type: string
          format: date-time
        endAt:
          type: string
          format: date-time

    CreateAllocationDTO:
      type: object
      allOf:
       - $ref: '#/components/schemas/UpdateAllocationDTO'
       - type: object
         properties:
           roomId:
             type: integer
             format: int64
           employeeName:
             type: string
           employeeEmail:
             type: string

    AllocationDTO:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateAllocationDTO'
      properties:
        id:
          type: integer
          format: int64

    ResponseError:
      type: object
      required:
        - errorCode
        - field
      properties:
        field:
          type: string
        errorCode:
          type: string

  responses:
    UnprocessableEntity:
      description: The server understands the content type of the request but was unable to process the contained
        instructions.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ResponseError'

  parameters:
    orderBy:
      name: orderBy
      in: query
      description: Field to order by
      schema:
        type: string

    limit:
      name: limit
      in: query
      description: Maximum number of returned records
      schema:
        type: integer

    page:
      name: page
      in: query
      description: The page of records to fetch (0 index based)
      schema:
        type: integer

    apiKey:
      name: api-key
      in: header
      description: The API key to authenticate the request
      required: true
      schema:
        type: string

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []