# =================================
# = Spring
# =================================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-44-194-167-63.compute-1.amazonaws.com:5432/ddtvfta3pdn67j
    username: egqpbguqyeaukn
  flyway:
    locations: classpath:/db/migration/postgresql